
kind: pipeline
type: exec
name: Build

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    commands:
      - docker build .

name: Deployment
  - name: run
    commands:
      - docker-compose up --build -d

