kind: pipeline
type: exec
name: default
platform:
  os: linux
  arch: amd64

steps:
  - name: build
    commands:
      - docker-compose -p Crisp_Telegram_bot build

  - name: run
    commands:
      - docker-compose -p Crisp_Telegram_bot up -d
    when:
      status:
        - success

